# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
source /etc/profile.d/aliases.sh

alias cls='clear'
alias pull='git pull'
alias gpl='git pull'
alias origin='git pull origin'
alias a='git add .'
alias gc='git commit -m'
alias ac='git commit -a -m' # 将暂存区提交更新
alias push='git push'
alias pf='git push -f' # 强制推送

# 规范提交
alias feat='featFun() { git commit -m "feat: $1";}; featFun'                 # commit feat
alias fix='fixFun() { git commit -m "fix: $1";}; fixFun'                     # commit fix
alias refactor='refactorFun() { git commit -m "refactor: $1";}; refactorFun' # commit refactor
alias style='styleFun() { git commit -m "style: $1";}; styleFun'             # commit style ``
alias built='builtFun() { git commit -m "built $1";}; builtFun'              # commit built

alias auto='auto() { git add .; git commit -m "$1"; git push; }; auto' # 自动push
alias gcp='cpFun() { git commit -m "$1"; git push; }; cpFun'           # 自动commit push

alias s='git status'
alias d='git diff'
alias gs='git stash'
alias gsp='git stash pop'

alias check='checkFun() { git branch -a | grep "$1";}; checkFun'
alias walk='walkFun() { git checkout $1;}; walkFun'
alias new='newFun() { git checkout -b $1;}; newFun'

# 撤销
alias soft='git reset --soft HEAD^'                                     # 撤销commit
alias reset='backHard() { git reset --hard $1; git push -f;}; backHard' # 回退任意版本
alias back='git reset --hard HEAD^ && git push -f'                      # 回退上个

# 修改
alias m='git commit --amend'                             # 修改commit信息
alias log='git log --pretty=format:"%h - %an, %ar : %s"' # 查看版本

alias host='code /c/Windows/System32/drivers/etc/hosts'

alias copyId='copyIdFun(){ ssh-copy-id -i ~/.ssh/id_rsa.pub $1@$2;}; copyIdFun'
alias sp='scpFun(){ scp -r js built resources views css fonts includes $1@$2:/var/www/html;}; scpFun'
alias sp142='scpFun(){ scp -r js built resources views personal_login css fonts includes root@172.16.65.142:/var/www/html;}; scpFun'

# alias
alias ls='ls -F --color=auto --show-control-chars'
alias ll='ls -l'
alias grep='grep --color'
# proxy
# default socks5
alias setproxy="export ALL_PROXY=socks5://127.0.0.1:7890"
# company socks5 ssh tunnel
alias setproxy1="export ALL_PROXY=socks5://59.175.233.194:8181"
# reset proxy
alias unsetproxy="unset ALL_PROXY"

alias cip="curl -i http://ip.cn"
# clear
alias c="clear"
# git
alias gpl="git pull"
alias gpu="git push"
alias gs="git status"
alias glg="git log --stat"
alias gc='git config credential.helper store'

# npm and yarn
alias ns="npm start"
alias ys="yarn run serve"

# shortcut path
alias gw="cd d:/code"

# ls

alias lsa="sudo ls -la --color=auto"
alias l='ls -la'

# scp
alias scp142="scp -r js built resources views personal_login css fonts includes root@172.16.65.142:/var/www/html"
alias scp146="scp -r js built resources views personal_login css fonts includes root@172.16.65.146:/var/www/html"

case "$TERM" in
xterm*)
  # The following programs are known to require a Win32 Console
  # for interactive usage, therefore let's launch them through winpty
  # when run inside `mintty`.
  for name in node ipython php php5 psql python2.7; do
    case "$(type -p "$name".exe 2>/dev/null)" in
    '' | /usr/bin/*) continue ;;
    esac
    alias $name="winpty $name.exe"
  done
  ;;
esac

alias cls='clear'
alias pull='git pull'
alias origin='git pull origin'
alias a='git add .'
alias gc='git commit -m'
alias ac='git commit -a -m' # 将暂存区提交更新
alias push='git push'
alias pf='git push -f' # 强制推送

# 规范提交
alias feat='featFun() { git commit -m "feat: $1";}; featFun'                 # commit feat
alias fix='fixFun() { git commit -m "fix: $1";}; fixFun'                     # commit fix
alias refactor='refactorFun() { git commit -m "refactor: $1";}; refactorFun' # commit refactor
alias style='styleFun() { git commit -m "style: $1";}; styleFun'             # commit style ``
alias built='builtFun() { git commit -m "built $1";}; builtFun'              # commit built

alias auto='auto() { git add .; git commit -m "$1"; git push; }; auto' # 自动push
alias gcp='cpFun() { git commit -m "$1"; git push; }; cpFun'           # 自动commit push

alias s='git status'
alias d='git diff'
alias gs='git stash'
alias gsp='git stash pop'

alias check='checkFun() { git branch -a | grep "$1";}; checkFun'
alias walk='walkFun() { git checkout $1;}; walkFun'
alias new='newFun() { git checkout -b $1;}; newFun'

# 撤销
alias soft='git reset --soft HEAD^'                                     # 撤销commit
alias reset='backHard() { git reset --hard $1; git push -f;}; backHard' # 回退任意版本
alias back='git reset --hard HEAD^ && git push -f'                      # 回退上个

# 修改
alias m='git commit --amend'                             # 修改commit信息
alias log='git log --pretty=format:"%h - %an, %ar : %s"' # 查看版本

alias copyId='copyIdFun(){ ssh-copy-id -i ~/.ssh/id_rsa.pub $1@$2;}; copyIdFun'
alias async='scpFun(){ scp -r js built resources views personal_login css fonts includes $1@$2:/var/www/html;}; scpFun'
alias sp142='scpFun(){ scp -r js built resources views personal_login css fonts includes root@172.16.65.142:/var/www/html;}; scpFun'

alias econf='code ~/.bash_profile'
alias ewezterm='code ~/.wezterm.lua'
alias envim='code ~/.config/nvim/init.vim'
alias ehost='code /c/Windows/System32/drivers/etc/hosts'

# git@172.16.203.254:hanxiaoxiang/ngconsole.git
# git@172.16.203.254:baiyu/ngconsole_resources.git
# git@172.16.203.254:huangzijie/view-front.git
export GIT_INNER_PREFIX=http://172.16.203.254
export GIT_OUTER_PREFIX=http://14f74814.r3.cpolar.top

export NG_SURFIX_URL=/hanxiaoxiang/ngconsole.git
export RE_SURFIX_URL=/baiyu/ngconsole_resources.git
export VF_SURFIX_URL=/huangzijie/view-front.git
export WORK=d:/code
export SPACE=d:/code/ngconsole
export TSPACE=d:/code/view-front

alias chng='git remote set-url origin $GIT_OUTER_PREFIX$NG_SURFIX_URL'
alias clng='git clone $GIT_OUTER_PREFIX$NG_SURFIX_URL'
alias chng1='git remote set-url origin $GIT_INNER_PREFIX$NG_SURFIX_URL'
alias chre='git remote set-url origin $GIT_OUTER_PREFIX$RE_SURFIX_URL'
alias clre='git clone $GIT_OUTER_PREFIX$RE_SURFIX_URL'
alias chre1='git remote set-url origin $GIT_INNER_PREFIX$RE_SURFIX_URL'
alias chvf='git remote set-url origin $GIT_OUTER_PREFIX$VF_SURFIX_URL'
alias clvf='git clone $GIT_OUTER_PREFIX$VF_SURFIX_URL'
alias chvf1='git remote set-url origin $GIT_INNER_PREFIX$VF_SURFIX_URL'

alias wk='cd $WORK'
alias sp='cd $SPACE'
alias ts='cd $TSPACE'
alias setproxy='export https_proxy=http://127.0.0.1:7890;export http_proxy=http://127.0.0.1:7890;export all_proxy=socks5://127.0.0.1:7890'
alias unsetproxy='export https_proxy="";http_proxy="";export all_proxy=""'
alias config='source ~/.bash_profile'
alias pn='pnpm'


echo "PROMPT_COMMAND='history -a'">> ~/.bash_profile
echo "PROMPT_COMMAND='history -a'">> ~/.bashrc
PROMPT_COMMAND='history -a'
PROMPT_COMMAND='history -a'
PROMPT_COMMAND='history -a'
PROMPT_COMMAND='history -a'
PROMPT_COMMAND='history -a'
PROMPT_COMMAND='history -a'
